social/m/urls.py
from django.urls import path
from . import views


app_name = "m"
urlpatterns = [
    path('', views.home, name="home"),
    path('profile_list', views.profile_list, name="profile_list"),
    path('profile/<int:pk>', views.profile, name="profile"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_register, name="register"),
    path('update_user/', views.update_user, name="update_user"),
    path('tweet_like/<int:pk>', views.tweet_like, name="tweet_like"),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('m.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/m/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create a tweet model.
class Tweet(models.Model):
    user = models.ForeignKey(User, related_name="tweets", on_delete=models.DO_NOTHING)
    body = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="tweet_like", blank=True)

    # Keep count of likes
    def number_of_likes(self):
        return self.likes.count()

    def __str__(self):
        return(
            f"{self.user} "            
            f"({self.created_at:%d-%m-%Y %H:%M}): "            
            f"{self.body}"            
        )

# Create a User Profile Model.
class Profile(models.Model):
    # Link each Profile to a User. If a User is deleted, their Profile is also deleted.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Set up a many-to-many relationship to the same model ('self') for followers.
    # 'symmetrical=False' means if A follows B, B doesn't necessarily follow A.
    # 'related_name' allows querying who follows a user.
    # 'blank=True' allows a profile to follow no other profiles.
    follows = models.ManyToManyField("self",
                                     related_name="followed_by",
                                     symmetrical=False,
                                     blank=True)
    
    # Info on when user last modified their data.
    date_modified = models.DateTimeField(auto_now=True)
    # Image upload for User if want to
    profile_image = models.ImageField(null=True, blank=True, upload_to="images/")
    
    def __str__(self):
        return self.user.username

# Signal function to create a Profile when a User is created.
# @receiver to connect the 'create_profile' function to the User model's 'post_save' signal.    
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    # Check if it's a new user instance.
    if created:
        # Create a Profile instance for the new user.
        user_profile = Profile(user=instance)
        user_profile.save()
        # Have the user follow themselves automatically.
        user_profile.follows.set([instance.profile.id])
        user_profile.save()

social/m/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django import forms
from .models import Tweet, Profile

# Profiles extras form
class ProfilePicForm(forms.ModelForm):
    profile_image = forms.ImageField(label="Profile Picture")

    class Meta:
        model = Profile
        fields = ('profile_image', )

class TweetForm(forms.ModelForm):
    """Create a tweet body form."""
    class Meta:
        model = Tweet
        fields = ['body']  # Specify the fields to be used from the model
        widgets = {
            'body': forms.Textarea(
                attrs={
                    "placeholder": "Enter your Tweet!",
                    "class": "form-control",
                }
            ),
        }
        labels = {
            'body': '',  # Hides the label for the body field
        }


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)
        
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user_id = self.instance.id if self.instance else None

        if User.objects.filter(username=username).exclude(id=user_id).exists():
            raise ValidationError("A user with that username already exists.")
        return username

social/m/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Profile, Tweet
from .forms import TweetForm, SignUpForm, ProfilePicForm

def home(request):
    tweet = None  # Initialize tweet
    if request.user.is_authenticated:
        form = TweetForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                tweet = form.save(commit=False)
                tweet.user = request.user
                tweet.save()
                messages.success(request, "Your tweet has been successfully posted...")
                return redirect('m:home')

        context = {
            'form': form,
            'tweet': tweet  # Include tweet only if it's defined
        }

        tweets = Tweet.objects.all().order_by("-created_at")
        context['tweets'] = tweets  # Add tweets to the context
        return render(request, "m/home.html", context)

    else:
        tweets = Tweet.objects.all().order_by("-created_at")
        context = {
            'tweets': tweets  # Add tweets to the context
        }
        return render(request, "m/home.html", context)



def profile_list(request):
    if request.user.is_authenticated:
        """Retrieve a list of profiles excluding the users profile."""
        profiles = Profile.objects.exclude(user=request.user)
        return render(request, 'm/profile_list.html', {'profiles': profiles})
    else:
        messages.error(request, "You must be logged in to view this page...")
        return redirect('m:home')
    

def profile(request, pk):
    """User profile page."""
    if request.user.is_authenticated:
        tweets = Tweet.objects.filter(user_id=pk).order_by("-created_at")  # get tweets from latest to oldest with "-created_at".
        profile = Profile.objects.get(user_id=pk)
        # Post form logic.
        if request.method == 'POST':
            # Get current user ID
            current_user = request.user.profile
            # Get form data
            action = request.POST['follow']
            # Decide to follow or unfollow.
            if action == "unfollow":
                current_user.follows.remove(profile)
            elif action == "follow":
                current_user.follows.add(profile)
            # Save the profile.
            current_user.save()

        context = {
            'tweets': tweets,
            'profile': profile
        }

        return render(request, 'm/profile.html', context)
    else:
        messages.error(request, "You must be logged in to view this page...")
        return redirect('m:home')


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Logged in successfully...")
            return redirect('m:home')
        else:
            messages.error(request, "Incorrect login details. Please try again.")
            context = {}
            return render(request, 'm/home.html', context)


def user_logout(request):
    logout(request)
    messages.success(request, "You have logged out...")
    return redirect('m:home')


def user_register(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            # Log in User
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "Registration successful. Welcome to M!")
            return redirect('m:home')
        else:
            messages.warning(request, "Registration failed. Please try again...")

            return render(request, 'm/home.html', {'form': form})
        

def update_user(request):
    """User profile update page."""
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        profile_user = Profile.objects.get(user__id=request.user.id)

        # Get forms.
        user_form = SignUpForm(request.POST or None, request.FILES or None, instance=current_user)
        profile_form = ProfilePicForm(request.POST or None, request.FILES or None, instance=profile_user)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            login(request, current_user)
            messages.success(request, "Your profile has been updated...")
            return redirect('m:home')
        
        context = {
            'user_form': user_form,
            'profile_form': profile_form,
        }
        return render(request, 'm/update_user.html', context)
    else:
        messages.error(request, "You must be logged in to view this page!")
        return redirect('m:home')

def tweet_like(request, pk):
    """Tweet like/unlike."""
    if request.user.is_authenticated:
        tweet = get_object_or_404(Tweet, id=pk)
        if tweet.likes.filter(id=request.user.id).exists():
            tweet.likes.remove(request.user)
        else:
            tweet.likes.add(request.user)

        return redirect('m:home')

    else:
        messages.error(request, "You must be logged in to view this page...")
        return redirect('m:home')

social/m/templates/m/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  </head>
  <body>

    {% include 'm/navbar.html' %}
      <br/>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>          
        {% endfor %}
      {% endif %}

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->

    <!-- Script to redirect user to Registration Modal if incorrect login details -->
    {% if messages %}
    <script type="text/javascript">
        $(document).ready(function() {
            var showRegisterModal = false;
            {% for message in messages %}
            if ("{{ message.tags }}" === "warning") {
                showRegisterModal = true;
            }
            {% endfor %}
            if (showRegisterModal) {
                $('#registerModal').modal('show');  // Modal ID
            }
        });
    </script>
    {% endif %}

      <!-- Script to redirect user to login Modal if incorrect login details -->
      {% if messages %}
      <script type="text/javascript">
          $(document).ready(function() {
              var showLoginModal = false;
              {% for message in messages %}
              if ("{{ message.tags }}" === "error") {
                  showLoginModal = true;
              }
              {% endfor %}
              if (showLoginModal) {
                  $('#loginModal').modal('show');  // Modal ID
              }
          });
      </script>
      {% endif %}

  </body>
</html>

social/m/templates/m/home.html
{% extends 'm/base.html' %}
{% load static %}

{% block content %}

<div class="container text-center">
  <div class="row">
    <div class="col-8">
      <h2>Welcome to M</h2>
      {% for tweet in tweets %}
      <div class="alert alert-primary" role="alert">
        <div class="container">
          <div class="row">
            <div class="col-2">
              {% if tweet.user.profile.profile_image %}
              <img src="{{ tweet.user.profile.profile_image.url }}" width=100 height=100 class="rounded-circle" alt="{{ tweet.user.username }}">
              {% else %}
              <img src="{% static 'images/default_logo.png' %}" class="img-fluid rounded-start" alt="Default profile pic">
              {% endif %}
            </div>
              <div class="col-10">
                ({{ tweet.created_at }})
                <strong>{{ tweet.user }}</strong><br/>
                {{ tweet.body }}<br/>
                {{ tweet.number_of_likes }} Likes - 
                {% if user in tweet.likes.all %}
                  <a href="{% url 'm:tweet_like' tweet.id %}">Unlike</a>
                {% else %}
                <a href="{% url 'm:tweet_like' tweet.id %}">Like</a>
                {% endif %}

              </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="col-4">
      <br/><br/>
      {% if form %}
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Tweet</button>
      </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

social/m/templates/m/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'm:home' %}">M</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'm:profile_list' %}">Profile List</a>
          </li>
        </ul>

          <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'm:profile' request.user.id %}">Hi {{ user }},</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'm:logout' %}">Logout</a>
            </li>
          </ul>
            
          {% else %}

          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link btn btn-link" data-bs-toggle="modal" data-bs-target="#registerModal">Register</a>
            </li>                   
              <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <div class="modal-header text-center">
                      <h1 class="modal-title fs-5" id="registerModalLabel">Register</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="col-md-6 offset-md-3">
                        <form method="POST" action="{% url 'm:register' %}">
                            {% csrf_token %}

                            {{ form.as_p }}

                            <div class="modal-footer justify-content-center">
                              <button type="submit" class="btn btn-primary">Register</button>
                            </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>               
          </ul>

            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link btn btn-link" data-bs-toggle="modal" data-bs-target="#loginModal">Login</a>
              </li>                   
                <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header text-center">
                        <h1 class="modal-title fs-5" id="loginModalLabel">Login</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <div class="col-md-6 offset-md-3">
                          <form method="POST" action="{% url 'm:login' %}">
                              {% csrf_token %}
                              <div class="mb-3">
                                <input type="text" class="form-control" name="username" placeholder="Username" required>
                              </div>
                              <br/>
                              <div class="mb-3">
                                <input type="password" class="form-control" name="password" placeholder="Password" required>
                              </div>
                              <br/>
                              <div class="modal-footer justify-content-center">
                                <button type="submit" class="btn btn-primary">Login</button>
                              </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </li>               
            </ul>
          {% endif %}
        
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light" type="submit">Search</button>
        </form>
      </div>
    </div>

  </nav>

social/m/templates/m/profile.html
{% extends 'm/base.html' %}
{% load static %}

{% block content %}

  {% if profile %}
    <div class="container text-center">
      <div class="row">
        <div class="col-8">
          <h2>{{ profile.user.username }}'s profile</h2>
          {% if tweets %}
            {% for tweet in tweets %}
            <div class="alert alert-primary" role="alert">
              <div class="container">
                <div class="row">
                  <div class="col-2">
                    {% if profile.profile_image %}
                    <img src="{{ profile.profile_image.url }}" width=100 height=100 class="rounded-circle" alt="{{ profile.user.username }}">
                    {% else %}
                    <img src="{% static 'images/default_logo.png' %}" class="img-fluid rounded-start" alt="Default profile pic">
                    {% endif %}
                  </div>
                    <div class="col-10">
                      {{ tweet.body }}
                    </div>
                </div>
              </div>
            </div>
            {% endfor %}
          {% endif %}
        </div>

        <div class="col-4">
          <br/><br/>

          {% if profile.profile_image %}
          <img src="{{ profile.profile_image.url }}" style="border-radius: 50%; width: 200px; height: 200px;">
          {% endif %}
          <br/><br/>

            <div class="card">
              <h5 class="card-header">Follows</h5>
                <div class="card-body">
                  <p class="card-text">
                    {% for following in profile.follows.all %}
                    <a href="{% url 'm:profile' following.user.id %}" style="text-decoration: none; color: inherit;">@{{ following }}</a><br/>
                    {% endfor %}
                    <br/>
                  </p>
                </div>
            </div><br/>
          
            <div class="card">
                <h5 class="card-header">Followed By</h5>
                  <div class="card-body">
                    <p class="card-text">
                      {% for following in profile.followed_by.all %}
                      <a href="{% url 'm:profile' following.user.id %}" style="text-decoration: none; color: inherit;">@{{ following }}</a><br/>
                      {% endfor %}
                      <br/>
                    </p>
                  </div>
            </div><br/>
            
              <form method=POST>
                {% csrf_token %}
                {% if profile in user.profile.follows.all %}
                  <button class="btn btn-outline-danger" name="follow" value="unfollow"
                  type="submit">Unfollow @{{ profile.user.username }}</button>
                {% else %}
                  <button class="btn btn-outline-primary" name="follow" value="follow"
                  type="submit">Follow @{{ profile.user.username }}</button>
                {% endif %}
              </form><br/>
              
              {% if request.user.id == profile.user.id %}
                <a href="{% url 'm:update_user' %}" class="btn btn-outline-primary">Update Profile</a>
              {% endif %}
        </div>
      </div>
    </div>
  {% endif %}

{% endblock %}

social/m/templates/m/profile_list.html
{% extends 'm/base.html' %}
{% load static %}

{% block content %}
  <h2>Profile List</h2>
  <br/>
  {% if profiles %}
    {% for profile in profiles %}
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            {% if profile.profile_image %}
            <img src="{{ profile.profile_image.url }}" width=150 height=100 class="img-fluid rounded-start" alt="{{ profile.user.username }}">
            {% else %}
            <img src="{% static 'images/default_logo.png' %}" class="img-fluid rounded-start" alt="Users profile pic">
            {% endif %}
          </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ profile.user.username }}</h5>
                <p class="card-text"><a href="{% url 'm:profile' profile.user.id %}" style="text-decoration: none; color: inherit;">@{{ profile.user.username|lower }}</a></p>
                <p class="card-text"><small class="text-muted">Last updated {{ profile.date_modified }}</small></p>
              </div>
            </div>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h2>No profiles found.</h2>
  {% endif %}
{% endblock content %}

social/m/templates/m/update_user.html
{% extends 'm/base.html' %}

{% block content %}

<div class="col-md-6 offset-md-3">
  <h2>Update User</h2>
  <br/>

  <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <br/>
    <button type="submit" class="btn btn-primary">Update</button>
  </form>

</div>
{% endblock %}